export const USER_STORAGE_VARIABLE = "@USER_STORAGE_KEY";
export const USER_STORAGE_ACCESS_TOKEN = "@USER_STORAGE_ACCESS_TOKEN";
export const USER_STORAGE_REFRESH_TOKEN = "@USER_STORAGE_REFRESH_TOKEN";
